import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import General from "./components/General";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });
//👇 Import Open Sans font
import { Open_Sans } from 'next/font/google'

//👇 Configure our font object
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className="main">
          <Navbar/>
          <General/>
          {children}
        </div>
        
      </body>
    </html>
  );
}
